# Generated by Django 5.2.5 on 2025-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('GESTIONNAIRE', 'Gestionnaire'), ('MEDECIN', 'Médecin'), ('PATIENTE', 'Patiente')], max_length=20),
        ),
    ]
