# Generated by Django 5.2.5 on 2025-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('GESTIONNAIRE', 'Gestionnaire'), ('MEDECIN', 'Médecin'), ('PATIENTE', 'Patiente')], max_length=20),
        ),
    ]
