# Generated by Django 5.2.5 on 2025-08-31 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('cle_authentification', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_installation', models.DateTimeField(default=django.utils.timezone.now)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hospital_module.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='LotCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=255, unique=True)),
                ('date_livraison', models.DateTimeField(default=django.utils.timezone.now)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='hospital_module.hopital')),
                ('livre_par_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_livres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistreCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('uid_rfid', models.CharField(max_length=255, unique=True)),
                ('est_viacareme', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ENREGISTREE', 'Enregistrée'), ('LIVREE', 'Livrée'), ('AFFECTEE', 'Affectée'), ('PERDUE', 'Perdue'), ('ENDOMMAGEE', 'Endommagée')], default='ENREGISTREE', max_length=20)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('enregistre_par_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('ATTRIBUTION', 'Attribution')], max_length=20)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cible_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cards_module.device')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hospital_module.hopital')),
                ('lance_par_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_lancees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotCarteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cards_module.lotcarte')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_details', to='cards_module.registrecarte')),
            ],
            options={
                'unique_together': {('lot', 'registre')},
            },
        ),
    ]
