# Generated by Django 5.2.5 on 2025-09-16 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_module', '0001_initial'),
        ('hospital_module', '0002_hopital_zone_de_sante'),
        ('patiente__module', '0003_patiente_creer_a_hopital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteAttribuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribuee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_attribuees', to=settings.AUTH_USER_MODEL)),
                ('carte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='cards_module.registrecarte')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='hospital_module.hopital')),
                ('patiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='patiente__module.patiente')),
            ],
            options={
                'db_table': 'carte_attribuee',
                'unique_together': {('carte', 'patiente')},
            },
        ),
    ]
