# Generated by Django 5.2.5 on 2025-09-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_module', '0002_carteattribuee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionscan',
            name='hopital',
        ),
    ]
