# Generated by Django 5.2.5 on 2025-09-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_module', '0003_remove_sessionscan_hopital'),
        ('hospital_module', '0002_hopital_zone_de_sante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hospital_module.hopital'),
        ),
        migrations.AlterField(
            model_name='device',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
