# Generated by Django 5.2.5 on 2025-09-30 21:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grossesse_module', '0002_alter_auditaction_action_type'),
        ('medical_module', '0002_medecin_hopitaux'),
        ('patiente__module', '0003_patiente_creer_a_hopital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('RENDEZVOUS', 'Rendez-vous'), ('VACCINATION', 'Vaccination'), ('LECTURE', 'Lecture')], max_length=50)),
                ('code_otp', models.CharField(max_length=6)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('uid_rfid', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otps_crees', to=settings.AUTH_USER_MODEL)),
                ('patiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_otps', to='patiente__module.patiente')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('hauteur_uterine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mouvements_foetaux', models.BooleanField(default=False)),
                ('oedemes', models.BooleanField(default=False)),
                ('presentation', models.CharField(blank=True, max_length=50, null=True)),
                ('examens_prescrits', models.TextField(blank=True, null=True)),
                ('examens_resultats', models.TextField(blank=True, null=True)),
                ('medicaments_prescrits', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('prochaine_consultation', models.DateField(blank=True, null=True)),
                ('otp_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grossesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='grossesse_module.grossesse')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='medical_module.medecin')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('otp_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grossesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='grossesse_module.grossesse')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='medical_module.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccin_nom', models.CharField(max_length=100)),
                ('date_administration', models.DateField(default=django.utils.timezone.now)),
                ('destine_a', models.CharField(choices=[('MERE', 'Mère'), ('ENFANT', 'Enfant')], default='MERE', max_length=10)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('otp_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grossesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='grossesse_module.grossesse')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='medical_module.medecin')),
            ],
        ),
    ]
