# Generated by Django 5.2.5 on 2025-09-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionotp',
            name='created_par',
        ),
    ]
