# Generated by Django 5.2.5 on 2025-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_module', '0002_remove_actionotp_created_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='tension_arterielle',
        ),
        migrations.AddField(
            model_name='consultation',
            name='BS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='BodyTemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='DiastolicBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='HeartRate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='SystolicBP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
