# Generated by Django 5.2.5 on 2025-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='zone_de_sante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
