# Generated by Django 5.2.5 on 2025-09-01 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identification', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_carte', models.BooleanField(default=False)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('lien_parente', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_patiente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patiente',
            },
        ),
    ]
