# Generated by Django 5.2.5 on 2025-09-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patiente__module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiente',
            name='contact_urgence_nom',
        ),
        migrations.RemoveField(
            model_name='patiente',
            name='contact_urgence_telephone',
        ),
        migrations.RemoveField(
            model_name='patiente',
            name='lien_parente',
        ),
    ]
