# Generated by Django 5.2.5 on 2025-09-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module', '0002_hopital_zone_de_sante'),
        ('patiente__module', '0002_remove_patiente_contact_urgence_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiente',
            name='creer_a_hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientes_creees', to='hospital_module.hopital'),
        ),
    ]
