# Generated by Django 5.2.5 on 2025-09-17 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patiente__module', '0003_patiente_creer_a_hopital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_GROSSESSE', 'Création grossesse'), ('UPDATE_GROSSESSE', 'Modification grossesse'), ('CREATE_DOSSIER_OBS', 'Création dossier obstétrical'), ('UPDATE_DOSSIER_OBS', 'Modification dossier obstétrical')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patiente__module.patiente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('patiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_dossier', to='patiente__module.patiente')),
            ],
        ),
        migrations.CreateModel(
            name='Grossesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('dpa', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('PERDUE', 'Perdue')], default='EN_COURS', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grossesses', to='patiente__module.patiente')),
            ],
            options={
                'unique_together': {('patiente', 'statut')},
            },
        ),
        migrations.CreateModel(
            name='DossierObstetrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geste', models.IntegerField(default=0)),
                ('parite', models.IntegerField(default=0)),
                ('date_ddr', models.DateField(blank=True, null=True)),
                ('groupage_sanguin', models.CharField(blank=True, max_length=10, null=True)),
                ('rhesus', models.CharField(blank=True, max_length=5, null=True)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('antecedents_obstetricaux', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('prise_medicaments', models.TextField(blank=True, null=True)),
                ('autres_infos', models.TextField(blank=True, null=True)),
                ('risque_grossesse', models.CharField(blank=True, max_length=255, null=True)),
                ('grossesse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='grossesse_module.grossesse')),
            ],
        ),
    ]
