# Generated by Django 5.2.5 on 2025-09-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_GROSSESSE', 'Création grossesse'), ('UPDATE_GROSSESSE', 'Modification grossesse'), ('CREATE_DOSSIER_OBS', 'Création dossier obstétrical'), ('UPDATE_DOSSIER_OBS', 'Modification dossier obstétrical'), ('ACCESS_DOSSIER', 'Accès dossier obstétrical')], max_length=50),
        ),
    ]
