# Generated by Django 5.2.5 on 2025-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grossesse_module', '0002_alter_auditaction_action_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grossesse',
            unique_together=set(),
        ),
    ]
