# Generated by Django 5.2.5 on 2025-09-01 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medecin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medecin',
            },
        ),
        migrations.CreateModel(
            name='MedecinHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='hospital_module.hopital')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='medical_module.medecin')),
            ],
            options={
                'db_table': 'medecin_hopital',
                'constraints': [models.UniqueConstraint(fields=('medecin', 'hopital'), name='uniq_medecin_hopital')],
            },
        ),
    ]
