# Generated by Django 5.2.5 on 2025-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module', '0001_initial'),
        ('medical_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='hopitaux',
            field=models.ManyToManyField(related_name='hopitaux_medecins', through='medical_module.MedecinHopital', to='hospital_module.hopital'),
        ),
    ]
